- name: enable ansible repository to get the latest ansible release
  apt_repository:
    repo:  ppa:ansible/ansible
    state: present

- name: install neccesary packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - software-properties-common
    - ansible

- name: install dci agent
  pip:
    name: git+https://github.com/redhat-cip/python-dciclient.git
    state: present
    editable: false

- name: download ansible-dci from github
  git:
    repo: https://github.com/redhat-cip/dci-ansible.git
    dest: /tmp/git_files/

- name: create directories
  file:
    path: /usr/share/dci/
    state: directory

- name: install ansible-dci modules/plugins
  shell: "cp -r /tmp/git_files/{{ item }} /usr/share/dci/{{ item }}"
  with_items:
    - callback
    - modules
    - module_utils

- name: source dci_credentials from non login prompts such as su
  lineinfile:
    path: /etc/bash.bashrc
    line: source /etc/profile.d/dci_credentials.sh
    state: present
