---
- name: Ensure required variables are defined
  fail: msg="{{ item }} value missing and is required"
  when: "{{ item }} is not defined"
  with_items:
    - dci_user
    - dci_control_url
    - dci_api_key

- name: install EPEL
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: install pip
  package:
    name: python-pip
    state: present

- name: install a couple of neccesary python packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - junit_xml   # allows usage of the junit callback plugin
    - xunitmerge  # allows user to merge junit into one file

- name: set up connection information
  template:
    src: env.sh
    dest: /etc/profile.d/dci_credentials.sh
    owner: root
    group: root
    mode: 0744
  # no_log: true
